spring.application.name=employee-backend

spring.datasource.url=jdbc:mysql://mysql-22deb7df-mrniteshmourya9565-371d.g.aivencloud.com:16755/employees_details?ssl-mode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=YOUR_AIVEN_PASSWORD

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update